name: residential_management
description: The app for security guards to read QR codes and search info
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

scripts:
  codegen: dart run build_runner build
  codegen-dev: dart run build_runner watch
  get-schema: get-graphql-schema http://localhost:8080/v1/graphql >
    lib/graphql/schema.graphql
  update-splash: dart run flutter_native_splash:create
  update-coverage-badge: dart run covadge coverage/lcov.info .
  update-coverage:
    - flutter test --coverage --test-randomize-ordering-seed random
    - lcov --remove coverage/lcov.info  '**/__generated__/*' '*.gr.*' 'env.g.dart'  -o coverage/lcov.info
    - derry update-coverage-badge
  open-coverage-report:
    - genhtml coverage/lcov.info -o coverage/
    - open coverage/index.html

dependencies:
  auto_route: ^7.4.0
  bloc: ^8.1.2
  envied: ^0.3.0+3
  equatable: ^2.0.5
  ferry: ^0.14.2+1
  ferry_flutter: ^0.8.1
  ferry_hive_store: ^0.5.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.0
  gql_http_link: ^1.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.3
  build_runner: ^2.4.5
  change_app_package_name: ^1.1.0
  covadge: ^0.0.1
  envied_generator: ^0.3.0+3
  ferry_generator: ^0.8.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.24.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
